Minimize changes -> maximize sanity

diff --git a/.github/workflows/changelog.yaml b/.github/workflows/changelog.yaml
--- a/.github/workflows/changelog.yaml
+++ b/.github/workflows/changelog.yaml
@@ -7,7 +7,7 @@
 #   - label is added or removed
 # Runs on merge queues, but just passes, because it is a required check.
 
-name: Changelog-Testing
+name: Changelog
 
 on:
   pull_request_target:
@@ -19,7 +19,7 @@ on:
 jobs:
   validate-changelog:
     runs-on: ubuntu-24.04
-    fail_on_error: true
+    # fail_on_error: true
     if: "contains(github.event_name, 'pull_request')"
     env:
       PR_HAS_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'no-changelog') }}
@@ -41,3 +41,20 @@ jobs:
           git fetch origin master:refs/remotes/origin/master
 
           ./scripts/check_changelog_fragments.sh
+
+  check-changelog:
+    name: Changelog
+    runs-on: ubuntu-24.04
+    needs: validate-changelog
+    if: always()
+    env:
+      FAILED: ${{ contains(needs.*.result, 'failure') }}
+    steps:
+      - name: exit
+        run: |
+          echo "failed=${{ env.FAILED }}"
+          if [[ "$FAILED" == "true" ]] ; then
+            exit 1
+          else
+            exit 0
+          fi
