run in 8 core runner

diff --git a/.github/workflows/integration-comment.yml b/.github/workflows/integration-comment.yml
--- a/.github/workflows/integration-comment.yml
+++ b/.github/workflows/integration-comment.yml
@@ -202,14 +202,6 @@ jobs:
           max_attempts: 3
           command: bash scripts/ci-integration-test.sh datadog-traces
 
-      - name: e2e-datadog-logs
-        if: ${{ contains(github.event.comment.body, '/ci-run-integration-e2e-datadog-logs') || contains(github.event.comment.body, '/ci-run-all') }}
-        uses: nick-fields/retry@v2
-        with:
-          timeout_minutes: 35
-          max_attempts: 3
-          command: bash scripts/ci-integration-test.sh e2e-datadog-logs
-
       - name: dnstap
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-dnstap')
           || contains(github.event.comment.body, '/ci-run-integration-all')
@@ -454,11 +446,39 @@ jobs:
           max_attempts: 3
           command: bash scripts/ci-integration-test.sh webhdfs
 
+  e2e-tests:
+    needs: prep-pr
+    runs-on: [linux, ubuntu-20.04-8core]
+    if: contains(github.event.comment.body, '/ci-run-integration-e2e-datadog-logs')
+      || contains(github.event.comment.body, '/ci-run-integration-all')
+      || contains(github.event.comment.body, '/ci-run-all')
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          submodules: "recursive"
+
+      - run: sudo npm -g install @datadog/datadog-ci
+
+      - run: docker image prune -af ; docker container prune -f
+      - name: e2e-datadog-logs
+        if: ${{ contains(github.event.comment.body, '/ci-run-integration-e2e-datadog-logs')
+          || contains(github.event.comment.body, '/ci-run-integration-all')
+          || contains(github.event.comment.body, '/ci-run-all') }}
+        uses: nick-fields/retry@v2
+        with:
+          timeout_minutes: 35
+          max_attempts: 3
+          command: bash scripts/ci-integration-test.sh e2e-datadog-logs
+
   update-pr-status:
     name: Signal result to PR
     runs-on: ubuntu-latest
-    needs: integration-tests
+    needs:
+      - integration-tests
+      - e2e-tests
     if: always() && (contains(github.event.comment.body, '/ci-run-integration') || contains(github.event.comment.body, '/ci-run-all'))
+    env:
+      FAILED: ${{ contains(needs.*.result, 'failure') }}
     steps:
       - name: Generate authentication token
         id: generate_token
@@ -466,6 +486,7 @@ jobs:
         with:
           app_id: ${{ secrets.GH_APP_DATADOG_VECTOR_CI_APP_ID }}
           private_key: ${{ secrets.GH_APP_DATADOG_VECTOR_CI_APP_PRIVATE_KEY }}
+
       - name: Validate issue comment
         if: github.event_name == 'issue_comment'
         uses: tspascoal/get-user-teams-membership@v3
@@ -475,12 +496,22 @@ jobs:
           GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
 
       - name: (PR comment) Get PR branch
+        if: github.event_name == 'issue_comment' && env.FAILED != 'true'
         uses: xt0rted/pull-request-comment-branch@v2
         id: comment-branch
 
-      - name: (PR comment) Submit PR result as ${{ needs.integration-tests.result }}
+      - name: (PR comment) Submit PR result as success
+        if: github.event_name == 'issue_comment' && env.FAILED != 'true'
         uses: myrotvorets/set-commit-status-action@v2.0.0
         with:
           sha: ${{ steps.comment-branch.outputs.head_sha }}
           token: ${{ secrets.GITHUB_TOKEN }}
-          status: ${{ needs.integration-tests.result }}
+          status: 'success'
+
+      - run: |
+          echo "failed=${{ env.FAILED }}"
+          if [[ "$FAILED" == "true" ]] ; then
+            exit 1
+          else
+            exit 0
+          fi
