chore(tests): Add end-to-end tests with the Datadog Agent (#18538)
* start

* check spelling allow

* reorg

* try consume a log

* trying on logs

* saving progress on vdev changes

* more vdev drafts

* Revert "more vdev drafts"

This reverts commit 758a06a58931c617c901df91fd2deacacb61f317.

* Revert "saving progress on vdev changes"

This reverts commit 7a692907b23ea5267c789597af0c3f2f588ba3d9.

* extract Vector instance to its own container

* cleanup the compose file

* Generate logs on fly

* cleanup

* cleanup

* cleanup

* remove sleep

* add to CI

* spell checker

* fix issue with DD changes detection

* more workflow fix

* increase timeout as experiment

* update vector config for log endpoint field

* touch up

* start

* CI

* feedback bg

* add scaffolding for the differentiation of series API versions

* fix(datadog_metrics sink): fix the integration tests which weren't actually validating anything

* fix workflows

* clippy

* fix filter for traces

* add first pass

* add testing coverage

* cargo.lock

* reduce duplicated code

* cleanup

* clippy

* feedback ds: remove check for sort by name

* feedback ds: extend unit tests for v2

* feedback ds: extend the int test coverage

* Revert "feedback ds: remove check for sort by name"

This reverts commit c95a326c30a471e660742b6e354ab5d73e1201de.

* add explicit sort check

* add env var for v1 support

* check events

* add note in deprecations

* feedback ds

* ds feedback logs PR

* config pain; start aggregation

* feedback ds: move to scripts/e2e

* add v6 and v7 agent versions to test against

* remove dead code allow

* move to e2e dir

* improve comparison logic

* code reduction

* add sketches, some reorg

* cleanup

* add notes about the e2e prefix needed

* re-use runner image

* fixes

* e2e tests now run in CI

* clippy

* remove unused struct

* true up the int test comment changes

* cleanup

* rework the massaging and comparison model

* compare to all versions

* cleanup and address TODO for sketches

* feedback ds: workflows

* feedback ds: simpler compose

* feedback ds: agent versions clarity

* feedback ds: comments

* clippy

* touchups

* feedback bg: assert_eq

* increase timeout workflow

* run in 8 core runner

* check

* separate e2e workflow

* comment

* fix workflows

* prune timing

* allow build_all option to start subcommand

* hack to bypass this temporary issue with CI

* feedback bg

* feedback bg

* feedback ds: metric type check

* add descriptive comment

* spelling

* chore(vdev): refactor e2e tests into own subcommand (#19666)

* merge conflict

* update workflows

* rename

* fix e2e logic

* fix e2e

* fix e2e

* script usage

* touchups to workflows

* separate dockerfile for the e2e tests

* add the Dockerfile

diff --git a/.github/workflows/integration-comment.yml b/.github/workflows/integration-comment.yml
--- a/.github/workflows/integration-comment.yml
+++ b/.github/workflows/integration-comment.yml
@@ -100,7 +100,7 @@ jobs:
           # First one requires more time, as we need to build the image from scratch
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh amqp
+          command: bash scripts/ci-int-e2e-test.sh int amqp
 
       - name: appsignal
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-appsignal')
@@ -110,7 +110,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh appsignal
+          command: bash scripts/ci-int-e2e-test.sh int appsignal
 
       - name: aws
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-aws')
@@ -120,7 +120,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh aws
+          command: bash scripts/ci-int-e2e-test.sh int aws
 
       - name: axiom
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-axiom')
@@ -130,7 +130,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh axiom
+          command: bash scripts/ci-int-e2e-test.sh int axiom
 
       - name: azure
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-azure')
@@ -140,7 +140,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh azure
+          command: bash scripts/ci-int-e2e-test.sh int azure
 
       - name: clickhouse
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-clickhouse')
@@ -150,7 +150,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh clickhouse
+          command: bash scripts/ci-int-e2e-test.sh int clickhouse
 
       - name: databend
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-databend')
@@ -160,7 +160,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh databend
+          command: bash scripts/ci-int-e2e-test.sh int databend
 
       - name: datadog-agent
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-datadog-agent')
@@ -170,7 +170,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh datadog-agent
+          command: bash scripts/ci-int-e2e-test.sh int datadog-agent
 
       - name: datadog-logs
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-datadog-logs')
@@ -180,7 +180,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh datadog-logs
+          command: bash scripts/ci-int-e2e-test.sh int datadog-logs
 
       - name: datadog-metrics
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-datadog-metrics')
@@ -190,7 +190,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh datadog-metrics
+          command: bash scripts/ci-int-e2e-test.sh int datadog-metrics
 
       - name: datadog-traces
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-datadog-traces')
@@ -200,7 +200,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh datadog-traces
+          command: bash scripts/ci-int-e2e-test.sh int datadog-traces
 
       - name: dnstap
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-dnstap')
@@ -210,7 +210,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh dnstap
+          command: bash scripts/ci-int-e2e-test.sh int dnstap
 
       - run: docker image prune -af --filter=label!=vector-test-runner=true ; docker container prune -f
 
@@ -222,7 +222,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh docker-logs
+          command: bash scripts/ci-int-e2e-test.sh int docker-logs
 
       - name: elasticsearch
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-elasticsearch')
@@ -232,7 +232,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh elasticsearch
+          command: bash scripts/ci-int-e2e-test.sh int elasticsearch
 
       - name: eventstoredb
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-eventstoredb')
@@ -242,7 +242,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh eventstoredb
+          command: bash scripts/ci-int-e2e-test.sh int eventstoredb
 
       - name: fluent
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-fluent')
@@ -252,7 +252,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh fluent
+          command: bash scripts/ci-int-e2e-test.sh int fluent
 
       - name: gcp
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-gcp')
@@ -262,7 +262,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh gcp
+          command: bash scripts/ci-int-e2e-test.sh int gcp
 
       - name: greptimedb
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-greptimedb')
@@ -272,7 +272,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh greptimedb
+          command: bash scripts/ci-int-e2e-test.sh int greptimedb
 
       - name: humio
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-humio')
@@ -282,7 +282,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh humio
+          command: bash scripts/ci-int-e2e-test.sh int humio
 
       - name: http-client
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-http-client')
@@ -292,7 +292,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh http-client
+          command: bash scripts/ci-int-e2e-test.sh int http-client
 
       - name: influxdb
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-influxdb')
@@ -302,7 +302,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh influxdb
+          command: bash scripts/ci-int-e2e-test.sh int influxdb
 
       - name: kafka
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-kafka')
@@ -312,7 +312,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh kafka
+          command: bash scripts/ci-int-e2e-test.sh int kafka
 
       - name: logstash
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-logstash')
@@ -322,7 +322,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh logstash
+          command: bash scripts/ci-int-e2e-test.sh int logstash
 
       - name: loki
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-loki')
@@ -332,7 +332,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh loki
+          command: bash scripts/ci-int-e2e-test.sh int loki
 
       - name: mongodb
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-mongodb')
@@ -342,7 +342,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh mongodb
+          command: bash scripts/ci-int-e2e-test.sh int mongodb
 
       - run: docker image prune -af --filter=label!=vector-test-runner=true ; docker container prune -f
 
@@ -354,7 +354,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh nats
+          command: bash scripts/ci-int-e2e-test.sh int nats
 
       - name: nginx
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-nginx')
@@ -364,7 +364,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh nginx
+          command: bash scripts/ci-int-e2e-test.sh int nginx
 
       - name: opentelemetry
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-opentelemetry')
@@ -374,7 +374,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh opentelemetry
+          command: bash scripts/ci-int-e2e-test.sh int opentelemetry
 
       - name: postgres
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-postgres')
@@ -384,7 +384,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh postgres
+          command: bash scripts/ci-int-e2e-test.sh int postgres
 
       - name: prometheus
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-prometheus')
@@ -394,7 +394,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh prometheus
+          command: bash scripts/ci-int-e2e-test.sh int prometheus
 
       - name: pulsar
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-pulsar')
@@ -404,7 +404,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh pulsar
+          command: bash scripts/ci-int-e2e-test.sh int pulsar
 
       - name: redis
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-redis')
@@ -414,7 +414,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh redis
+          command: bash scripts/ci-int-e2e-test.sh int redis
 
       - name: shutdown
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-shutdown')
@@ -424,7 +424,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh shutdown
+          command: bash scripts/ci-int-e2e-test.sh int shutdown
 
       - name: splunk
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-splunk')
@@ -434,7 +434,7 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh splunk
+          command: bash scripts/ci-int-e2e-test.sh int splunk
 
       - name: webhdfs
         if: ${{ contains(github.event.comment.body, '/ci-run-integration-webhdfs')
@@ -444,13 +444,48 @@ jobs:
         with:
           timeout_minutes: 30
           max_attempts: 3
-          command: bash scripts/ci-integration-test.sh webhdfs
+          command: bash scripts/ci-int-e2e-test.sh int webhdfs
+
+  e2e-tests:
+    needs: prep-pr
+    runs-on: [linux, ubuntu-20.04-8core]
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          submodules: "recursive"
+
+      - run: sudo npm -g install @datadog/datadog-ci
+
+      - run: docker image prune -af ; docker container prune -f
+      - name: e2e-datadog-logs
+        if: ${{ contains(github.event.comment.body, '/ci-run-e2e-datadog-logs')
+          || contains(github.event.comment.body, '/ci-run-integration-all')
+          || contains(github.event.comment.body, '/ci-run-all') }}
+        uses: nick-fields/retry@v2
+        with:
+          timeout_minutes: 35
+          max_attempts: 3
+          command: bash scripts/ci-int-e2e-test.sh e2e datadog-logs
+
+      - name: datadog-e2e-metrics
+        if: ${{ contains(github.event.comment.body, '/ci-run-e2e-datadog-metrics')
+          || contains(github.event.comment.body, '/ci-run-integration-all')
+          || contains(github.event.comment.body, '/ci-run-all') }}
+        uses: nick-fields/retry@v2
+        with:
+          timeout_minutes: 35
+          max_attempts: 3
+          command: bash scripts/ci-int-e2e-test.sh e2e datadog-metrics
 
   update-pr-status:
     name: Signal result to PR
     runs-on: ubuntu-latest
-    needs: integration-tests
+    needs:
+      - integration-tests
+      - e2e-tests
     if: always() && (contains(github.event.comment.body, '/ci-run-integration') || contains(github.event.comment.body, '/ci-run-all'))
+    env:
+      FAILED: ${{ contains(needs.*.result, 'failure') }}
     steps:
       - name: Generate authentication token
         id: generate_token
@@ -458,6 +493,7 @@ jobs:
         with:
           app_id: ${{ secrets.GH_APP_DATADOG_VECTOR_CI_APP_ID }}
           private_key: ${{ secrets.GH_APP_DATADOG_VECTOR_CI_APP_PRIVATE_KEY }}
+
       - name: Validate issue comment
         if: github.event_name == 'issue_comment'
         uses: tspascoal/get-user-teams-membership@v3
@@ -467,12 +503,22 @@ jobs:
           GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
 
       - name: (PR comment) Get PR branch
+        if: github.event_name == 'issue_comment' && env.FAILED != 'true'
         uses: xt0rted/pull-request-comment-branch@v2
         id: comment-branch
 
-      - name: (PR comment) Submit PR result as ${{ needs.integration-tests.result }}
+      - name: (PR comment) Submit PR result as success
+        if: github.event_name == 'issue_comment' && env.FAILED != 'true'
         uses: myrotvorets/set-commit-status-action@v2.0.0
         with:
           sha: ${{ steps.comment-branch.outputs.head_sha }}
           token: ${{ secrets.GITHUB_TOKEN }}
-          status: ${{ needs.integration-tests.result }}
+          status: 'success'
+
+      - run: |
+          echo "failed=${{ env.FAILED }}"
+          if [[ "$FAILED" == "true" ]] ; then
+            exit 1
+          else
+            exit 0
+          fi
