chore(ci): Move most CI checks to merge queue (#17340)
Introduces a number of changes to our project's GH workflows:
- There is a more limited set of tests that run on each PR commit,
and the rest were moved to the merge queue.
- Most workflows can be triggered manually by a team member
though a comment on a PR.
- Integration tests are run on PR commits if they touch the files
specific to that component.

diff --git a/.github/workflows/k8s_e2e.yml b/.github/workflows/k8s_e2e.yml
--- a/.github/workflows/k8s_e2e.yml
+++ b/.github/workflows/k8s_e2e.yml
@@ -1,33 +1,33 @@
+# K8s E2E Suite
+#
+# This workflow runs under any of the following conditions:
+#    - manual dispatch in GH UI
+#    - on a PR commit if the kubernetes_logs source was changed
+#    - in the merge queue
+#    - on a schedule at midnight UTC Tue-Sat
+#    - on demand by either of the following comments in a PR:
+#        - '/ci-run-k8s'
+#        - '/ci-run-all'
+#
+# If the workflow trigger is the nightly schedule, all the k8s versions
+# are run in the matrix, otherwise, only the latest is run.
+
 name: K8S E2E Suite
 
 on:
   workflow_dispatch:
-  push:
-    branches:
-      - master
-    paths:
-      - ".github/workflows/k8s_e2e.yml"
-      - ".cargo/**"
-      - "benches/**"
-      - "lib/**"
-      - "proto/**"
-      - "scripts/**"
-      - "src/**"
-      - "tests/**"
-      - "build.rs"
-      - "Cargo.lock"
-      - "Cargo.toml"
-      - "Makefile"
-      - "rust-toolchain"
-      - "distribution/**"
   pull_request:
+  issue_comment:
+    types: [created]
+  merge_group:
+    types: [checks_requested]
+  schedule:
+    # At midnight UTC Tue-Sat
+    - cron: '0 0 * * 2-6'
 
 concurrency:
-  # For pull requests, cancel running workflows, for master, run all
-  #
-  # `github.event.number` exists for pull requests, otherwise fall back to SHA
-  # for master
-  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
+  group: ${{ github.workflow }}-${{ github.event.number || github.event.issue.id || github.event.merge_group.base_sha || github.event.schedule || github.sha }}
+
   cancel-in-progress: true
 
 env:
@@ -42,34 +42,81 @@ env:
   PROFILE: debug
 
 jobs:
+  changes:
+    if: github.event_name != 'issue_comment' || (github.event.issue.pull_request &&
+          (contains(github.event.comment.body, '/ci-run-k8s') || contains(github.event.comment.body, '/ci-run-all')))
+    uses: ./.github/workflows/changes.yml
+    with:
+      base_ref: ${{ github.event.pull_request.base.ref }}
+      head_ref: ${{ github.event.pull_request.head.ref }}
+    secrets: inherit
+
   build-x86_64-unknown-linux-gnu:
     name: Build - x86_64-unknown-linux-gnu
     runs-on: [linux, ubuntu-20.04-8core]
-    if: |
-      !github.event.pull_request
-        || contains(github.event.pull_request.labels.*.name, 'ci-condition: k8s e2e tests enable')
-        || contains(github.event.pull_request.labels.*.name, 'ci-condition: k8s e2e all targets')
+    needs: changes
+    if: github.event_name != 'pull_request' || needs.changes.outputs.k8s == 'true'
     # cargo-deb requires a release build, but we don't need optimizations for tests
     env:
       CARGO_PROFILE_RELEASE_OPT_LEVEL: 0
       CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 256
       CARGO_INCREMENTAL: 0
     steps:
-      - uses: actions/checkout@v3
+      - name: Validate issue comment
+        if: github.event_name == 'issue_comment'
+        uses: tspascoal/get-user-teams-membership@v2
+        with:
+          username: ${{ github.actor }}
+          team: 'Vector'
+          GITHUB_TOKEN: ${{ secrets.GH_PAT_ORG }}
+
+      - name: (PR comment) Get PR branch
+        if: ${{ github.event_name == 'issue_comment' }}
+        uses: xt0rted/pull-request-comment-branch@v1
+        id: comment-branch
+
+      - name: (PR comment) Set latest commit status as pending
+        if: ${{ github.event_name == 'issue_comment' }}
+        uses: myrotvorets/set-commit-status-action@1.1.6
+        with:
+          sha: ${{ steps.comment-branch.outputs.head_sha }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+          status: pending
+
+      - name: (PR comment) Checkout PR branch
+        if: ${{ github.event_name == 'issue_comment' }}
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ steps.comment-branch.outputs.head_ref }}
+
+      - name: Checkout branch
+        if: ${{ github.event_name != 'issue_comment' }}
+        uses: actions/checkout@v3
+
       - uses: actions/cache@v3
         with:
           path: |
             ~/.cargo/registry
             ~/.cargo/git
           key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
+
       - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
       - run: bash scripts/environment/prepare.sh
       - run: echo "::add-matcher::.github/matchers/rust.json"
       - run: VECTOR_VERSION="$(cargo vdev version)" make package-deb-x86_64-unknown-linux-gnu
+
       - uses: actions/upload-artifact@v3
         with:
           name: e2e-test-deb-package
           path: target/artifacts/*
+
+      - name: (PR comment) Set latest commit status as 'failure'
+        uses: myrotvorets/set-commit-status-action@1.1.6
+        if: failure() && github.event_name == 'issue_comment'
+        with:
+          sha: ${{ steps.comment-branch.outputs.head_sha }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+          status: 'failure'
 
   # GitHub Actions don't support `matrix` at the job-level `if:` condition.
   # We apply this workaround - compute `matrix` in a preceding job, and assign
@@ -80,13 +127,19 @@ jobs:
   compute-k8s-test-plan:
     name: Compute K8s test plan
     runs-on: [linux, ubuntu-20.04-8core]
+    needs: changes
+    if: github.event_name != 'pull_request' || needs.changes.outputs.k8s == 'true'
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
-    if: |
-      !github.event.pull_request
-        || contains(github.event.pull_request.labels.*.name, 'ci-condition: k8s e2e tests enable')
-        || contains(github.event.pull_request.labels.*.name, 'ci-condition: k8s e2e all targets')
     steps:
+      - name: Validate issue comment
+        if: github.event_name == 'issue_comment'
+        uses: tspascoal/get-user-teams-membership@v2
+        with:
+          username: ${{ github.actor }}
+          team: 'Vector'
+          GITHUB_TOKEN: ${{ secrets.GH_PAT_ORG }}
+
       - uses: actions/github-script@v6.4.1
         id: set-matrix
         with:
@@ -101,11 +154,11 @@ jobs:
             // https://cloud.google.com/kubernetes-engine/docs/release-notes
             // https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar
             const kubernetes_version = [
-              { version: "v1.23.3", is_essential: true },
-              { version: "v1.22.5", is_essential: true },
-              { version: "v1.21.8", is_essential: true },
-              { version: "v1.20.14", is_essential: true },
-              { version: "v1.19.8" },
+              { version: "v1.23.3",  is_essential: true  },
+              { version: "v1.22.5",  is_essential: false },
+              { version: "v1.21.8",  is_essential: false },
+              { version: "v1.20.14", is_essential: false },
+              { version: "v1.19.8",  is_essential: false },
             ]
             const container_runtime = [
               "docker",
@@ -113,15 +166,10 @@ jobs:
               // https://github.com/kubernetes/minikube/issues/12928
               // "crio",
             ]
-            const ci_condition_label = 'ci-condition: k8s e2e all targets'
 
-            // Planing.
-            const is_in_pull_request = !!context.payload.pull_request;
-            const should_test_all_targets = (
-              !is_in_pull_request ||
-              context.payload.pull_request.labels.some(label => label.name === ci_condition_label)
-            )
-            const filter_targets = array => array.filter(val => should_test_all_targets || val.is_essential)
+            // Run all versions if triggered by nightly schedule. Otherwise only run latest.
+            const run_all = context.eventName == "schedule";
+            const filter_targets = array => array.filter(val => run_all || val.is_essential)
 
             const matrix = {
               minikube_version,
@@ -147,36 +195,82 @@ jobs:
       matrix: ${{ fromJson(needs.compute-k8s-test-plan.outputs.matrix) }}
       fail-fast: false
     steps:
-      - name: Checkout
+      - name: (PR comment) Get PR branch
+        if: ${{ github.event_name == 'issue_comment' }}
+        uses: xt0rted/pull-request-comment-branch@v1
+        id: comment-branch
+
+      - name: (PR comment) Checkout PR branch
+        if: ${{ github.event_name == 'issue_comment' }}
         uses: actions/checkout@v3
+        with:
+          ref: ${{ steps.comment-branch.outputs.head_ref }}
+
+      - name: Checkout branch
+        if: ${{ github.event_name != 'issue_comment' }}
+        uses: actions/checkout@v3
+
       - uses: actions/download-artifact@v3
         with:
           name: e2e-test-deb-package
           path: target/artifacts
+
       - name: Setup Minikube
         run: scripts/ci-setup-minikube.sh
         env:
           KUBERNETES_VERSION: ${{ matrix.kubernetes_version.version }}
           MINIKUBE_VERSION: ${{ matrix.minikube_version }}
           CONTAINER_RUNTIME: ${{ matrix.container_runtime }}
+
       - run: make test-e2e-kubernetes
         env:
           USE_MINIKUBE_CACHE: "true"
           SKIP_PACKAGE_DEB: "true"
           CARGO_INCREMENTAL: 0
 
-  master-failure:
-    name: master-failure
-    if: failure() && github.ref == 'refs/heads/master'
-    needs:
-      - build-x86_64-unknown-linux-gnu
-      - compute-k8s-test-plan
-      - test-e2e-kubernetes
-    runs-on: ubuntu-20.04
+      - name: (PR comment) Set latest commit status as failure
+        uses: myrotvorets/set-commit-status-action@1.1.6
+        if: failure() && github.event_name == 'issue_comment'
+        with:
+          sha: ${{ steps.comment-branch.outputs.head_sha }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+          status: 'failure'
+
+  final-result:
+    name: K8s E2E Suite
+    runs-on: ubuntu-latest
+    needs: test-e2e-kubernetes
+    if: |
+      always() && (github.event_name != 'issue_comment' || (github.event.issue.pull_request
+        && (contains(github.event.comment.body, '/ci-run-k8s') || contains(github.event.comment.body, '/ci-run-all'))))
+    env:
+      FAILED: ${{ contains(needs.*.result, 'failure') }}
     steps:
-    - name: Discord notification
-      env:
-        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
-      uses: Ilshidur/action-discord@0.3.2
-      with:
-        args: "Master k8s e2e tests failed: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}>"
+      - name: Validate issue comment
+        if: github.event_name == 'issue_comment'
+        uses: tspascoal/get-user-teams-membership@v2
+        with:
+          username: ${{ github.actor }}
+          team: 'Vector'
+          GITHUB_TOKEN: ${{ secrets.GH_PAT_ORG }}
+
+      - name: (PR comment) Get PR branch
+        if: success() && github.event_name == 'issue_comment'
+        uses: xt0rted/pull-request-comment-branch@v1
+        id: comment-branch
+
+      - name: (PR comment) Submit PR result as success
+        if: success() && github.event_name == 'issue_comment'
+        uses: myrotvorets/set-commit-status-action@1.1.6
+        with:
+          sha: ${{ steps.comment-branch.outputs.head_sha }}
+          token: ${{ secrets.GITHUB_TOKEN }}
+          status: 'success'
+
+      - run: |
+          echo "failed=${{ env.FAILED }}"
+          if [[ "$FAILED" == "true" ]] ; then
+            exit 1
+          else
+            exit 0
+          fi
