typo

diff --git a/.github/workflows/master_merge_queue.yml b/.github/workflows/master_merge_queue.yml
--- a/.github/workflows/master_merge_queue.yml
+++ b/.github/workflows/master_merge_queue.yml
@@ -224,5 +224,5 @@ jobs:
     steps:
       - name: exit
         run: |
-          echo "${{ FAILED }}"
-          exit ${{ FAILED }} == 'false'
+          echo "failed=${{ env.FAILED }}"
+          exit ${{ env.FAILED }} == 'false'
