re work the regression workflow

diff --git a/.github/workflows/regression_trusted.yml b/.github/workflows/regression_trusted.yml
--- a/.github/workflows/regression_trusted.yml
+++ b/.github/workflows/regression_trusted.yml
@@ -2,13 +2,22 @@ name: Regression Detector (trusted)
 
 
 on:
-  workflow_call:
+  # Don't want to run for each PR, but because GH doesn't allow specifying different required checks
+  # for pull request and merge queue, we need to "run" it in pull request, but in the jobs we will just auto pass.
+  pull_request:
+  workflow_run:
+    workflows: ["Regression Detector"]
+    types:
+      - completed
 
 jobs:
+  # This is the entry job which is required for all subsequent jobs in the workflow.
+  # If we don't run this job (such as in a pull request), then by consequence all downstream
+  # test jobs are not run. This allows us to not have to check for merge group in each job.
   compute-metadata:
     name: Compute metadata for regression experiments
     runs-on: ubuntu-22.04
-    #if: github.event_name != 'pull_request' && github.event.workflow_run.conclusion == 'success'
+    if: github.event_name != 'pull_request' && github.event.workflow_run.conclusion == 'success'
     outputs:
       cpus: ${{ steps.system.outputs.CPUS }}
       memory: ${{ steps.system.outputs.MEMORY }}
@@ -85,7 +94,7 @@ jobs:
             var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
-               run_id: ${{ github.run_id }},
+               run_id: ${{ github.event.workflow_run.id }},
             });
 
             var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
@@ -155,7 +164,7 @@ jobs:
             var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
-               run_id: ${{ github.run_id }},
+               run_id: ${{ github.event.workflow_run.id }},
             });
 
             var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
@@ -223,7 +232,7 @@ jobs:
             var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
-               run_id: ${{ github.run_id }},
+               run_id: ${{ github.event.workflow_run.id }},
             });
 
             var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
@@ -429,7 +438,7 @@ jobs:
           name: vector-submission-metadata
           path: ${{ runner.temp }}/
 
-      - name: Determine if introduced a regression
+      - name: Determine if PR introduced a regression
         env:
           RUST_LOG: info
         run: |
@@ -589,3 +598,21 @@ jobs:
             -f description='Analyze experimental results from Regression Detector failed.' \
             -f context='Regression Detector / analyze-experiment' \
             -f target_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+
+  # Always run this so that pull_request triggers are marked as success.
+  regression-check:
+    name: Regression Detection Suite
+    runs-on: ubuntu-latest
+    if: always()
+    needs: detect-regression
+    env:
+      FAILED: ${{ contains(needs.*.result, 'failure') }}
+    steps:
+      - name: exit
+        run: |
+          echo "failed=${{ env.FAILED }}"
+          if [[ "$FAILED" == "true" ]] ; then
+            exit 1
+          else
+            exit 0
+          fi
