do it all in regression

diff --git a/.github/workflows/regression_trusted.yml b/.github/workflows/regression_trusted.yml
--- a/.github/workflows/regression_trusted.yml
+++ b/.github/workflows/regression_trusted.yml
@@ -5,12 +5,15 @@ on:
     workflows: ["Regression Detector"]
     types:
       - completed
+  merge_group:
+    types: [checks_requested]
 
 jobs:
   compute-metadata:
     name: Compute metadata for regression experiments
     runs-on: ubuntu-22.04
-    if: >
+    if: |
+      github.event_name != 'merge_group' &&
       github.event.workflow_run.event == 'pull_request' &&
       github.event.workflow_run.conclusion == 'success'
     outputs:
@@ -593,3 +596,19 @@ jobs:
             -f description='Analyze experimental results from Regression Detector failed.' \
             -f context='Regression Detector / analyze-experiment' \
             -f target_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+
+  regression-check:
+    runs-on: ubuntu-latest
+    if: always()
+    needs: detect-regression
+    env:
+      FAILED: ${{ contains(needs.*.result, 'failure') }}
+    steps:
+      - name: exit
+        run: |
+          echo "failed=${{ env.FAILED }}"
+          if [[ "$FAILED" == "true" ]] ; then
+            exit 1
+          else
+            exit 0
+          fi
